// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuuG-ERz5YGDCXJ-IxdCOTYceaUXNlHCA',
    appId: '1:693980371086:web:ed96a3d4cb51be2bee91df',
    messagingSenderId: '693980371086',
    projectId: 'firedemo-aa4ef',
    authDomain: 'firedemo-aa4ef.firebaseapp.com',
    storageBucket: 'firedemo-aa4ef.appspot.com',
    measurementId: 'G-QZ94S601ZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjC41gyIfYrgfQ51ErxPhPWivGVt4-m6U',
    appId: '1:693980371086:android:18d28040d194cae4ee91df',
    messagingSenderId: '693980371086',
    projectId: 'firedemo-aa4ef',
    storageBucket: 'firedemo-aa4ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYsp6Ba2vFtxEoN3a9Sjb74WnMqfE8IFM',
    appId: '1:693980371086:ios:1e89b594a411cc08ee91df',
    messagingSenderId: '693980371086',
    projectId: 'firedemo-aa4ef',
    storageBucket: 'firedemo-aa4ef.appspot.com',
    iosBundleId: 'com.example.fireDemo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYsp6Ba2vFtxEoN3a9Sjb74WnMqfE8IFM',
    appId: '1:693980371086:ios:1e89b594a411cc08ee91df',
    messagingSenderId: '693980371086',
    projectId: 'firedemo-aa4ef',
    storageBucket: 'firedemo-aa4ef.appspot.com',
    iosBundleId: 'com.example.fireDemo1',
  );
}
